from typing import List
from decimal import Decimal
from src.util.models import Effect, Product, Substance

level_name_to_int = {
    "street_rat_i": 1,
    "street_rat_ii": 2,
    "street_rat_iii": 3,
    "street_rat_iv": 4,
    "street_rat_v": 5,
    "hoodium_i": 6,
    "hoodium_ii": 7,
    "hoodium_iii": 8,
    "hoodium_iv": 9,
    "hoodium_v": 10,
    "peddler_i": 11,
    "peddler_ii": 12,
    "peddler_iii": 13,
    "peddler_iv": 14,
    "peddler_v": 15,
    "hustler_i": 16,
    "hustler_ii": 17,
    "hustler_iii": 18,
    "hustler_iv": 19,
    "hustler_v": 20,
    "bagman_i": 21,
    "bagman_ii": 22,
    "bagman_iii": 23,
    "bagman_iv": 24,
    "bagman_v": 25,
    "enforcer_i": 26,
    "enforcer_ii": 27,
    "enforcer_iii": 28,
    "enforcer_iv": 29,
    "enforcer_v": 30,
    "shot_caller_i": 31,
    "shot_caller_ii": 32,
    "shot_caller_iii": 33,
    "shot_caller_iv": 34,
    "shot_caller_v": 35,
    "block_boss_i": 36,
    "block_boss_ii": 37,
    "block_boss_iii": 38,
    "block_boss_iv": 39,
    "block_boss_v": 40,
    "underlord_i": 41,
    "underlord_ii": 42,
    "underlord_iii": 43,
    "underlord_iv": 44,
    "underlord_v": 45,
    "baron_i": 46,
    "baron_ii": 47,
    "baron_iii": 48,
    "baron_iv": 49,
    "baron_v": 50,
    "kingpin_i+": 51,
    "max": 51,
}

level_int_to_name = {v: k for k, v in level_name_to_int.items()}

effects: List[Effect] = [
    Effect(name="anti_gravity", modificator=0.54),
    Effect(name="athletic", modificator=0.32),
    Effect(name="balding", modificator=0.30),
    Effect(name="bright_eyed", modificator=0.40),
    Effect(name="calming", modificator=0.10),
    Effect(name="calorie_dense", modificator=0.28),
    Effect(name="cyclopean", modificator=0.56),
    Effect(name="disorienting", modificator=0.00),
    Effect(name="electrifying", modificator=0.50),
    Effect(name="energizing", modificator=0.22),
    Effect(name="euphoric", modificator=0.18),
    Effect(name="explosive", modificator=0.00),
    Effect(name="focused", modificator=0.16),
    Effect(name="foggy", modificator=0.36),
    Effect(name="gingeritis", modificator=0.20),
    Effect(name="glowing", modificator=0.48),
    Effect(name="jennerising", modificator=0.42),
    Effect(name="laxative", modificator=0.00),
    Effect(name="long_faced", modificator=0.52),
    Effect(name="munchies", modificator=0.12),
    Effect(name="paranoia", modificator=0.00),
    Effect(name="refreshing", modificator=0.14),
    Effect(name="schizophrenia", modificator=0.00),
    Effect(name="sedating", modificator=0.26),
    Effect(name="seizure_inducing", modificator=0.00),
    Effect(name="shrinking", modificator=0.60),
    Effect(name="slippery", modificator=0.34),
    Effect(name="smelly", modificator=0.00),
    Effect(name="sneaky", modificator=0.24),
    Effect(name="spicy", modificator=0.38),
    Effect(name="thought_provoking", modificator=0.44),
    Effect(name="toxic", modificator=0.00),
    Effect(name="tropic_thunder", modificator=0.46),
    Effect(name="zombifying", modificator=0.58),
]


products: List[Product] = [
    # weed
    Product(
        name="og_kush",
        base_sell_price=Decimal("35.00"),
        buy_price=Decimal("30.00"),
        level=level_name_to_int["street_rat_i"],
        effects=["calming"],
    ),
    Product(
        name="sour_diesel",
        base_sell_price=Decimal("35.00"),
        buy_price=Decimal("35.00"),
        level=level_name_to_int["street_rat_iv"],
        effects=["refreshing"],
    ),
    Product(
        name="green_crack",
        base_sell_price=Decimal("35.00"),
        buy_price=Decimal("40.00"),
        level=level_name_to_int["hoodium_ii"],
        effects=["energizing"],
    ),
    Product(
        name="granddaddy_purple",
        base_sell_price=Decimal("35.00"),
        buy_price=Decimal("45.00"),
        level=level_name_to_int["hoodium_iv"],
        effects=["sedating"],
    ),
    # meth
    Product(
        name="low_quality_pesudo",
        base_sell_price=Decimal("70.00"),
        buy_price=Decimal("60.00"),
        level=level_name_to_int["hoodium_i"],
        effects=[],
    ),
    Product(
        name="pseudo",
        base_sell_price=Decimal("70.00"),
        buy_price=Decimal("80.00"),
        level=level_name_to_int["hustler_iii"],
        effects=[],
    ),
    Product(
        name="high_quality_pesudo",
        base_sell_price=Decimal("70.00"),
        buy_price=Decimal("110.00"),
        level=level_name_to_int["bagman_v"],
        effects=[],
    ),
    # cocaine
    Product(
        name="cocaine",
        base_sell_price=Decimal("150.00"),
        buy_price=Decimal("0.00"),
        level=level_name_to_int["hustler_ii"],
        effects=[],
    ),
]

substances: List[Substance] = [
    Substance(
        name="cuke",
        price=Decimal("2.00"),
        level=level_name_to_int["street_rat_i"],
        resulting_effect="energizing",
        side_effect_replacements={
            "euphoric": "laxative",
            "foggy": "cyclopean",
            "gingeritis": "thought_provoking",
            "munchies": "athletic",
            "slippery": "munchies",
            "sneaky": "paranoia",
            "toxic": "euphoric",
        },
    ),
    Substance(
        name="flu_medicine",
        price=Decimal("5.00"),
        level=level_name_to_int["hoodium_iv"],
        resulting_effect="sedating",
        side_effect_replacements={
            "athletic": "munchies",
            "calming": "bright_eyed",
            "cyclopean": "foggy",
            "electrifying": "refreshing",
            "euphoric": "toxic",
            "focused": "calming",
            "laxative": "euphoric",
            "munchies": "slippery",
            "shrinking": "paranoia",
            "thought_provoking": "gingeritis",
        },
    ),
    Substance(
        name="gasoline",
        price=Decimal("5.00"),
        level=level_name_to_int["hoodium_v"],
        resulting_effect="toxic",
        side_effect_replacements={
            "disorienting": "glowing",
            "electrifying": "disorienting",
            "energizing": "euphoric",
            "euphoric": "spicy",
            "gingeritis": "smelly",
            "jennerising": "sneaky",
            "laxative": "foggy",
            "munchies": "sedating",
            "paranoia": "calming",
            "shrinking": "focused",
            "sneaky": "tropic_thunder",
        },
    ),
    Substance(
        name="donut",
        price=Decimal("3.00"),
        level=level_name_to_int["street_rat_i"],
        resulting_effect="calorie_dense",
        side_effect_replacements={
            "anti_gravity": "slippery",
            "balding": "sneaky",
            "calorie_dense": "explosive",
            "focused": "euphoric",
            "jennerising": "gingeritis",
            "munchies": "calming",
            "shrinking": "energizing",
        },
    ),
    Substance(
        name="energy_drink",
        price = Decimal("6.00"),
        level=level_name_to_int["peddler_i"],
        resulting_effect="athletic",
        side_effect_replacements={
            "disorienting": "electrifying",
            "euphoric": "energizing",
            "focused": "shrinking",
            "foggy": "laxative",
            "glowing": "disorienting",
            "schizophrenia": "balding",
            "sedating": "munchies",
            "spicy": "euphoric",
            "tropic_thunder": "sneaky",
        },
    ),
    Substance(
        name="mouth_wash",
        price=Decimal("4.00"),
        level=level_name_to_int["hoodium_iii"],
        resulting_effect="balding",
        side_effect_replacements={
            "calming": "anti_gravity",
            "calorie_dense": "sneaky",
            "explosive": "sedating",
            "focused": "jennerising",
        },
    ),
    Substance(
        name="motor_oil",
        price=Decimal("6.00"),
        level=level_name_to_int["peddler_ii"],
        resulting_effect="slippery",
        side_effect_replacements={
            "energizing": "munchies",
            "euphoric": "sedating",
            "foggy": "toxic",
            "munchies": "schizophrenia",
            "paranoia": "anti_gravity",
        },
    ),
    Substance(
        name="banana",
        price=Decimal("2.00"),
        level=level_name_to_int["street_rat_i"],
        resulting_effect="gingeritis",
        side_effect_replacements={
            "calming": "sneaky",
            "cyclopean": "energizing",
            "disorienting": "focused",
            "energizing": "thought_provoking",
            "focused": "seizure_inducing",
            "long_faced": "refreshing",
            "paranoia": "jennerising",
            "smelly": "anti_gravity",
            "toxic": "smelly",
        },
    ),
    Substance(
        name="chili",
        price=Decimal("7.00"),
        level=level_name_to_int["peddler_iv"],
        resulting_effect="spicy",
        side_effect_replacements={
            "anti_gravity": "tropic_thunder",
            "athletic": "euphoric",
            "laxative": "long_faced",
            "munchies": "toxic",
            "shrinking": "refreshing",
            "sneaky": "bright_eyed",
        },
    ),
    Substance(
        name="iodine",
        price=Decimal("8.00"),
        level=level_name_to_int["hustler_i"],
        resulting_effect="jennerising",
        side_effect_replacements={
            "calming": "balding",
            "calorie_dense": "gingeritis",
            "euphoric": "seizure_inducing",
            "foggy": "paranoia",
            "refreshing": "thought_provoking",
            "toxic": "sneaky",
        },
    ),
    Substance(
        name="paracetamol",
        price=Decimal("3.00"),
        level=level_name_to_int["street_rat_i"],
        resulting_effect="sneaky",
        side_effect_replacements={
            "calming": "slippery",
            "electrifying": "athletic",
            "energizing": "paranoia",
            "focused": "gingeritis",
            "foggy": "calming",
            "glowing": "toxic",
            "munchies": "anti_gravity",
            "paranoia": "balding",
            "spicy": "bright_eyed",
            "toxic": "tropic_thunder",
        },
    ),
    Substance(
        name="viagra",
        price=Decimal("4.00"),
        level=level_name_to_int["hoodium_ii"],
        resulting_effect="tropic_thunder",
        side_effect_replacements={
            "athletic": "sneaky",
            "disorienting": "toxic",
            "euphoric": "bright_eyed",
            "laxative": "calming",
            "shrinking": "gingeritis",
        },
    ),
    Substance(
        name="horse_semen",
        price=Decimal("9.00"),
        level=level_name_to_int["hustler_iii"],
        resulting_effect="long_faced",
        side_effect_replacements={
            "anti_gravity": "calming",
            "gingeritis": "refreshing",
            "seizure_inducing": "energizing",
            "thought_provoking": "electrifying",
        },
    ),
    Substance(
        name="mega_bean",
        price=Decimal("7.00"),
        level=level_name_to_int["hustler_ii"],
        resulting_effect="foggy",
        side_effect_replacements={
            "athletic": "laxative",
            "calming": "glowing",
            "energizing": "cyclopean",
            "focused": "disorienting",
            "jennerising": "paranoia",
            "seizure_inducing": "focused",
            "shrinking": "electrifying",
            "slippery": "toxic",
            "sneaky": "calming",
            "thought_provoking": "energizing",
        },
    ),
    Substance(
        name="addy",
        price=Decimal("9.00"),
        level=level_name_to_int["hustler_ii"],
        resulting_effect="thought_provoking",
        side_effect_replacements={
            "explosive": "euphoric",
            "foggy": "energizing",
            "glowing": "refreshing",
            "long_faced": "electrifying",
            "sedating": "gingeritis",
        },
    ),
    Substance(
        name="battery",
        price=Decimal("8.00"),
        level=level_name_to_int["peddler_v"],
        resulting_effect="bright_eyed",
        side_effect_replacements={
            "cyclopean": "glowing",
            "electrifying": "euphoric",
            "euphoric": "zombifying",
            "laxative": "calorie_dense",
            "munchies": "tropic_thunder",
            "shrinking": "munchies",
        },
    ),
]